### ISSUE TITLE
Route table dump

### ISSUE THREAD

**Issue by branaway** [pk11/play-jaxrs#1]
Can the resolved route table be dumped out to file system so one can quickly find out the path resolution without going thru all the controllers code?

**Comment by pk11** [comment]
no, this solution is based on inline annotations. If you prefer a separate route file, you are likely better off with the standard router solution.

**Comment by branaway** [comment]
I was saying that I wanted to use a centralized routing table. I wanted that for eye viewing purpose so that I can quickly find out what controller is taking care of what route, very useful in debugging "Action not found" cases.
