### ISSUE TITLE
Cannot get a sample to work

### ISSUE THREAD

**Issue by branaway** [pk11/play-jaxrs#3]
Hi,

I followed the readme to create a simple app to test it out. I was not able to get it to work. Am I missing something obvious? The sample project is here: https://github.com/branaway/jaxtest

Thanks for your attention.

**Comment by pk11** [comment]
I will look into this.

**Comment by branaway** [comment]
it's a classloader issue. I need to set the play app class loader to the
forName() method to get it work.

2013/7/7 Peter Hausel notifications@github.com

**Comment by pk11** [comment]
@branaway I am not sure if I can follow. Do you have a link? Thanks Peter

**Comment by branaway** [comment]
private lazy val classes = ref.getStore.getTypesAnnotatedWith(classOf[Path].getName).asScala.map(Class.forName(_)).toSet

The Class.forName() will have to take a classloader from the play application to resolve classes loaded by play app. This app works because the class loader to load the Router is the same as the rest of the app. But it's different when the router is used as an dependency.

**Comment by pk11** [comment]
@branaway I could not replicate this problem but it does make sense to get the classloader explicitly from the app, so I will change that. I also noticed that in play `2.1.1` there were a few breaking changes around `JavaAction`-s, so I will update jaxrs accordingly (since right now it's only compatible with `2.1.0`).

**Comment by pk11** [comment]
@branaway I just pushed a new change. Can you please test with the master version (the minimum play requirement is now `2.1.2`?

I will publish a new version if it's working.

**Comment by branaway** [comment]
I can't get the test going since the jar generated by a publish-local
contains all the sample controllers etc in the play-jaxrs project, which
seem to interfere with my own controllers. Does the packaging include
excessive bagage?

2013/7/8 Peter Hausel notifications@github.com

**Comment by pk11** [comment]
the instructions are in the README file

`play -Djaxrs=only publish-local`

**Comment by branaway** [comment]
Ok, te problem I had was not related to the excessive sample code in the
package.

The way the application class loader was set in the router was a once in a
life time action and it would contain an outdated instance if the
application is reloaded. I believe the class loader need to be fetched
freshly every time the app is reloaded, of course that's in dev mode.

2013/7/9 Peter Hausel notifications@github.com

**Comment by pk11** [comment]
I believe that's what's happening now. If the app is reloaded so is the plugin which in return will mean a fresh classloader every time there is a change in dev mode. (also, I tested it with my sample app and my changes are picked up in dev mode)

**Comment by pk11** [comment]
Can you please confirm if https://github.com/pk11/play-jaxrs/commit/7215194a1a068c7fd64f15aec716066c6063f226 is fixing your issue? If so, I will republish and close this ticket

**Comment by pk11** [comment]
I think I see what you meant now - perhaps the router is not reloaded since it's just an external dependency on a play app. I am going to extend this project as a real play plugin which I believe should force the app to reload the plugin

**Comment by pk11** [comment]
Please see:
https://github.com/pk11/play-jaxrs/commit/10d9e4833898526f7bab87bbd098ef465a5a9fa4

also, the installation instructions were updated to (the project is shipped as a play plugin going forward.

**Comment by branaway** [comment]
yes, it seems to work fine.  I guess there's no plan to make a 2.1
compatible version, is there?

2013/7/9 Peter Hausel notifications@github.com

**Comment by pk11** [comment]
Since the underlying API has changed it would be much easier to stick to `2.1.2` (and above)

**Comment by pk11** [comment]
I will publish a new version today

**Comment by pk11** [comment]
published as `0.6`
